# https://docs.travis-ci.com/user/languages/dart/
language: dart
dart:
  - stable

before_script:
  # https://flutter.dev/docs/get-started/web
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter upgrade
  - flutter config --enable-web
  - flutter doctor

script:
  - sh ./build.sh

# Deploy configuration
# Note: Be sure region has the bucket and application in that region.
# Note: See the readme init instructions on how I created this project.
deploy:
  - provider: elasticbeanstalk
    edge: true
    skip_cleanup: true
    access_key_id:
      secure: "s5v0u+Y7nR+bnSrWafAaShr0vhc0sest8OfIJC9yUoosOypXht4NJ18rIIBm19ritiNPN9LMoQNxSfuR++5rQ+Ma8Q0MJDRKpLcym/ZonQ2p1uFzf7oYHV4uvQT96sTO/7ifam0r4B45hhRGvLr/SO0P639/P30a4HUBqtmKhKzl+iSOt1i4rl+rg58O+YqaVXyuuPRpHHO0PgmUZCov6JoifT9NOI0xAJzIAPv7xt9R8P2Y4MYE0IX53b7NjniqiO6+5bpF2ZguJa3rfbvRLNmKdh5KuC1vuHNB0HHhRQSLnI2Bpad/PJoLt7jDrZ5tYrRf85mrp8VyqFMTCHYLIn++S3rVF5dsxoyALv8/RsxO7OffNuRQH+9azpAzI5c8nAkatjsj4YC9IooOmxnHgWI4cyBb1wwPykYBM2fY4v+qxpPDffrBgxfzFzzg869pzGzm1KqCCwzbeEl2jmS+g9D+5ekpCX7z3Cw+M6rbuAMH4GZ1+qMAHB1NNgp4qsf9vS66dJygrCNYGyUi5rUqM9sCKys51l+FXhbuPuiZo00Atru4QOk+MIeJMwVJTHP7CeStcuIn4aFmO7xGLY+uYV+agHqKnMjsIYEwDfpBN/qz1U1up8FZRDuoClqomS6NmDL2DEwyt/Uqqg0K2a10SFYtV06MgPAWWUZLBCF+rBk="
    secret_access_key:
      secure: "Pq6j1BCaPkqR7Y37JPf4bho87uJaptSwUT93zkIHO7ClODSCs2sESOxreYDdT1DVQz0F8bjKkD8uzGP4vNlmtg+eIsKj2dxUjMtdnAKpSzVmTbfs8JaSr8lqIIMYiyXG9duKx4qdWbn1hpnZmBW2iaP/+cn6bJbVAjuz+a5N0Rgfot430NNa0jvyvKO4+U09byTmJfvbHUTFrW9pnJHojMIbOBJXNhxEJrzJOsrpmwBFPO+r/ZJvw9vjEpbl/h42paoRckGirW2HI577nlDYFp3976XqDUn682dpXw3b/AMyZn44LeTrMCGqxqeFLv3s2gA2b6pOFwxJZygW9U7TNqhU/w3IVGGzQjCe1Pu7W4lZCrEKKATT9u+Je0QL8xRASveckg25+dcZ682p39hy6aJibi9mnbAWFq3wLqnj/fB3l3tB8PMRswCmC5X2EdDjdaFyhOYEN9dFbSEmKFEIOVw5k9KUnIHWop5nMNMeNS9f/WpZZpaUjSDRggHAxQQ63RwIiYacA4IFylV5n5qa2cndz8V6WeaJq1NmI6zFgkL1ID1dt7HWa4FmUEzepucjbB5T7zMhQFUjxIjFRghytcS51kpCWjozP24CVS+176oHA117dEqdk+iMJCD9UBvi9RoJwmCZbgWlVzaoXOTsby5CMJOnZaEuhxtMaDKUhYk="
    region: "us-west-2"
    app: "debugging-dart-webserver"
    env: "dartserver-staging-v1"
    bucket_name: "donnelson-deploy-bucket"


    
# Run Travis CLI in this repo
# gem install travis

# Delete Travis Cache
# travis cache --com
# travis cache --com --delete

# Encrypt Secure Variables
# gem install travis
# travis login --github-token replace_with_github_personal_token
# cd to/this/repo
# travis encrypt xxx_replace_with_access_key_id
# travis encrypt xxx_replace_with_with_secret_key

# Note: Debug deployment on EC2: in the docker container, or EB dash logs, in file: /var/log/eb-activity.log